### ISSUE TITLE
Broken Link To GItHub In PyPi

### ISSUE THREAD

**Issue by shmuel44** [michaelachmann/gpt-cost-estimator#1]
I saw on the [PyDigger](https://pydigger.com/pypi/gpt-cost-estimator) site that there is a broken link to github.

In the `setup.py` file,
`url="https://github.com/michaelachmann/openai_cost_estimator",`
the correct one is `/gpt-cost-estimator`
the url is broken, 
i am opening a PR to fix it.

**Comment by michaelachmann** [comment]
Thank you for pointing out the mistake and fixing it!

**Comment by shmuel44** [comment]
My pleasure 😄
